/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
/*
import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UsersControllerService } from '../user/services/users-controller.service';
import { AuthenticationControllerService } from '../user/services/authentication-controller.service';
import { ProductControllerService } from '../product/services/product-controller.service';
import { PaymentControllerService } from '../payment/services/payment-controller.service';
import { InvoiceControllerService } from '../payment/services/invoice-controller.service';
import { OrderControllerService } from '../order/services/order-controller.service';
import { OrderLineControllerService } from '../order/services/order-line-controller.service';
import { AddressControllerService } from '../address/services/address-controller.service';
/**
 * Module that provides all services and configuration.
 */
/*
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UsersControllerService,
    AuthenticationControllerService,
    AddressControllerService,
    OrderControllerService,
    OrderLineControllerService,
    PaymentControllerService,
    InvoiceControllerService,
    ProductControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor(
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
*/
