/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface Category {
  categoryId?: number;
  description?: string;
  name?: string;
  products?: Array<Product>;
}
