/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Category } from '../models/category';
export interface ProductRequest {
  brandName?: string;
  buyNowPrice?: number;
  category: Category;
  colour?: string;
  description: string;
  isAvailableForBuyNow?: boolean;
  isSold?: boolean;
  productId?: number;
  productName: string;
  productSize?: string;
  quantity?: number;
  sellerId?: number;
  startingPrice?: number;
}
