/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Category } from './models/category';
export type { Product } from './models/product';
export type { ProductRequest } from './models/product-request';
export type { ProductResponse } from './models/product-response';
